import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const { version } = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'));

const content = `// Auto-generated by scripts/set-version.mjs — do not edit manually.
export const environment = { version: '${version}' };
`;

writeFileSync(resolve(root, 'src/environments/environment.ts'), content);
console.log(`Version set to ${version}`);
